# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0001_initial'),
        ('integrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginreg.User'),
        ),
    ]
